version: '1'
services:
  web:
    image: metti:1
    ports:
      - 80:80
      - 2525:2525
    depends_on:
      - db
  db:
    image: postgis/postgis:16-3.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: metti

