version: '1'
services:
  web:
    build: .
    ports:
      - 80:80
      - 2525:2525
    restart: always
  db:
    image: postgis/postgis:16-3.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: metti

